# Generated by Django 3.2 on 2021-06-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210427_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_key',
            field=models.CharField(max_length=1024),
        ),
    ]
