# Generated by Django 3.2 on 2021-06-06 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210605_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(to='chat.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='chat.profile'),
        ),
    ]
