# Generated by Django 3.2 on 2021-06-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210606_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.CharField(max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
