# Generated by Django 3.2 on 2021-06-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='display_name',
            field=models.CharField(default='asd', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
