# Generated by Django 3.2 on 2021-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='1px-transparent.gif', null=True, upload_to='static/images/room_images'),
        ),
    ]
