# Generated by Django 3.2 on 2021-06-15 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_message_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
    ]
