from os import path
import re
import json
from django import template
from django.utils.safestring import mark_safe
from django.templatetags.static import static

from django_chat.settings import DEV_SERVER_ROOT, DEV


def is_absolute_url(url):
    return re.match("^https?://", url)


register = template.Library()


def vite_manifest(entries_names):
    app_name = 'chat'
    manifest_filepath = path.join(app_name, 'static/manifest.json')

    if DEV:
        scripts = [
            f"{DEV_SERVER_ROOT}/@vite/client",
        ]

        for name in entries_names:
            scripts.append(f'{DEV_SERVER_ROOT}/chat/assets/{name}')

        styles = []
        return scripts, styles
    else:
        with open(manifest_filepath) as fp:
            manifest = json.load(fp)
        _processed = set()

        def _process_entries(names):
            scripts = []
            styles = []

            for name in names:
                if name in _processed:
                    continue

                # chunk = manifest[name]
                key = f'chat/assets/{name}'
                chunk = manifest[key] if key in manifest else manifest[name]

                import_scripts, import_styles = _process_entries(chunk.get('imports', []))
                scripts += import_scripts
                styles += import_styles

                scripts += [chunk['file']]
                styles += [css for css in chunk.get('css', [])]

                _processed.add(name)

            return scripts, styles

        return _process_entries(entries_names)


@register.simple_tag(name="vite_styles")
def vite_styles(*entries_names):
    """
    Populate an html template with styles generated by vite

    Usage::

        {% vite_styles 'main.js' 'other-entry.js' %}

    Examples::
        <head>
            ...
            {% vite_styles 'main.js' 'other-entry.js' %}
        </head>
    """
    _, styles = vite_manifest(entries_names)
    styles = map(lambda href: href if is_absolute_url(href) else static(href), styles)
    return mark_safe("\n".join(map(lambda href: f'<link rel="stylesheet" href="{href}" />', styles)))


@register.simple_tag(name="vite_scripts")
def vite_scripts(*entries_names):
    """
    Populate an html template with script tags generated by vite

    Usage::

        {% vite_scripts 'main.js' 'other-entry.js' %}

    Examples::
        <body>
            <!-- Your HTML -->
            {% vite_scripts 'main.js' 'other-entry.js' %}
        </body>
    """
    scripts, _ = vite_manifest(entries_names)
    scripts = map(lambda src: src if is_absolute_url(src) else static(src), scripts)
    return mark_safe("\n".join(map(lambda src: f'<script type="module" src="{src}"></script>', scripts)))
